#!/bin/bash

mod=Super

riverctl map normal $mod+Control E exit

# Autostart
riverctl spawn "~/.config/river/autostart.sh"
riverctl spawn "~/.config/river/inputs.sh"

# Configuration window
riverctl background-color 0x000000
riverctl border-color-focused 0x999999
riverctl border-color-unfocused 0x404040
riverctl border-color-urgent 0xf7bcf4
riverctl border-width 2

riverctl focus-follows-cursor disabled
riverctl set-cursor-warp disabled

# Inputs
riverctl keyboard-layout -model pc105 -options "grp:alt_shift_toggle" us,ua
riverctl set-repeat 30 280

riverctl xcursor-theme Bibata-Original-Ice 24

# Tiling
riverctl spawn "rivertile -view-padding 5 -main-ratio 0.5"
riverctl output-layout rivertile

riverctl map normal $mod+Alt Up send-layout-cmd rivertile "main-location top"
riverctl map normal $mod+Alt Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod+Alt Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod+Alt Left send-layout-cmd rivertile "main-location left"

riverctl map normal $mod+Control Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod+Control Right send-layout-cmd rivertile "main-ratio +0.05"

# River
riverctl map normal $mod W close

riverctl map normal $mod+Control R spawn "pkexec reboot"
riverctl map normal $mod+Control P spawn "pkexec poweroff"

riverctl map normal $mod+Control C spawn ~/.config/river/init

# Layout 
riverctl map normal $mod Right focus-view next
riverctl map normal $mod Left focus-view previous

# Move to next or prev
riverctl map normal $mod+Shift Right swap next
riverctl map normal $mod+Shift Left swap previous

# Apps
riverctl map normal $mod Return spawn foot
riverctl map normal $mod D spawn "\$(tofi-drun)"
riverctl map normal $mod C spawn "wl-copy \"\$(echo \$(cliphist list | tofi | cliphist decode))\""

# Mouse
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Modes
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen

# Workspaces
function get_tag {
	echo $((1 << ($1 - 1)))
}

for index in $(seq 1 9)
do
	tag=$(get_tag $index)

	riverctl map normal $mod $index set-focused-tags $tag

	riverctl map normal $mod+Shift $index set-view-tags $tag
done

riverctl map normal $mod Tab focus-previous-tags

# Functions(Keys)
for mode in normal locked
do
	riverctl map $mode None XF86Eject spawn "eject -T"

	riverctl map -repeat $mode None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1"
	riverctl map -repeat $mode None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 0"
	riverctl map -repeat $mode None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

	riverctl map -repeat $mode None XF86MonBrightnessUp spawn "brightnessctl set 5%+"
	riverctl map -repeat $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"

	riverctl map $mode None Print spawn grim
	riverctl map $mode Shift Print spawn "grim -g \"\$(slurp)\""
done

# Rules
#riverctl rule-add -app-id pavucontrol float
#riverctl rule-add -app-id Code tag $(get_tag 8)
#riverctl rule-add -app-id Google-chrome tag $(get_tag 9)
#riverctl rule-add -app-id google-chrome tag $(get_tag 9)
